#!/usr/bin/env python
"""
Extract station data using the efficient SELFE extract_mod python module.

Examples for commandline interface:

# extract elevation from /some/run/outputs and store netCDF files to outputDir
extractStation -v elev -d /some/run/outputs -o outputDir -s 2011-05-11 -e 2011-07-20

# extract vertical profile of temperature from /some/run/outputs and store netCDF files to outputDir
extractStation -v temp -p -d /some/run/outputs -o outputDir -s 2011-05-11 -e 2011-07-20

# same as above except for a model that is UTM coordinates (e.g. deb28 grid)
extractStation -v elev -d /some/run/outputs -o outputDir -s 2011-05-11 -e 2011-07-20 -c utm

# working example
extractStation -d /home/workspace/ccalmr42/karnat/runs/db28dev/run03/outputs/ -v elev -o tmp_net -s 2002-5-17 -e 2002-5-19 -c utm

Tuomas Karna 2012-10-10
"""

# just a wrapper to parseCommandLine method
from data.extractStation import *

if __name__=='__main__' :
  parseCommandLine()
