#!/usr/bin/env python
"""
Extract transect data using the efficient SELFE extract_mod python module.

Examples:

# extract vdff, -d data dir, -t defines transect bp file, -n transect name string, -o output dir, -s -e time range
extractTransect -d ~pturner/db29/run29/outputs/ -v vdff -t nchannel_fine.bp -n nchannel -o run29/transect -s 2012-5-1 -e 2012-5-17

Tuomas Karna 2012-11-16
"""

# just a wrapper to parseCommandLine method
from crane.data import extractTransect

if __name__=='__main__' :
  extractTransect.parseCommandLine()
