#!/usr/bin/env python
"""
Script for generating bottom friction Cd plots.

Tuomas Karna 2013-03-01
"""
# just a wrapper to parseCommandLine method
from data.generateSaltIntrusion import *

if __name__=='__main__' :
  parseCommandLine()
