#!/usr/bin/env python
"""
Computes various skill metrics comparing model time series against reference.

Tuomas Karna 2013-11-07
"""

# just a wrapper to parseCommandLine method
from crane.data import computeSkillMetrics

if __name__=='__main__' :
  computeSkillMetrics.parseCommandLine()
