#!/usr/bin/env python
"""
Flux computation routine for SELFE netcdf outputs.

This routine reguires hvel.67.nc and dihv.71 files, and *.70 files for all
the tracers.

Tuomas Karna 2014-10-10
"""

# just a wrapper to parseCommandLine method
from crane.data import selfeFluxes

if __name__=='__main__':
  selfeFluxes.parseCommandLine()
