#!/usr/bin/env python
"""
Computes regional volume metrics from SELFE *.63.nc outputs.

Generalized version of computePlumeMetrics.py
"""

# just a wrapper to parseCommandLine method
from crane.data import computeVolumes

if __name__ == '__main__':
    computeVolumes.parseCommandLine()
