#!/usr/bin/env python
"""
A script for extracting data from Matlab surrogate model profile time series,
and storing it in netCDF format.

Tuomas Karna 2013-11-06

"""

# just a wrapper to parseCommandLine method
from crane.data import convSurrogateOutputToNC

if __name__ == '__main__':
    convSurrogateOutputToNC.parseCommandLine()
