#!/usr/bin/env python
"""
Script for generating bottom friction Cd plots.

Tuomas Karna 2013-03-01
"""
# just a wrapper to parseCommandLine method
from crane.data import generateSaltIntrusion

if __name__=='__main__' :
  generateSaltIntrusion.parseCommandLine()
