#!/usr/bin/env python
"""
Computes and plots residual salinity transport profile from
velocity and salinity profiles.

Tuomas Karna 2013-11-08

"""

# just a wrapper to parseCommandLine method
from plotting import plotSaltTranspProfile

if __name__=='__main__' :
  plotSaltTranspProfile.parseCommandLine()
