#!/usr/bin/env python
"""
Create bed_flux.61.nc files.

Examples:

Jesse Lopez 2014-09-26
"""

# just a wrapper to parseCommandLine method
from crane.files import makeBedFluxFile as mbff

if __name__ == '__main__':
    mbff.parseCommandLine()
