#!/usr/bin/env python
"""
A script for generating time series plots.

Examples:

# plot all salt time series from saturn02
makeTimeSeriesPlots -s 2012-5-1 -e 2012-5-10 -o tmp/images */data/stations/saturn02/saturn02.*.salt/*.nc

# plot all salt time series from saturn02, show image do not store
makeTimeSeriesPlots -s 2012-5-1 -e 2012-5-10 */data/stations/saturn02/saturn02.*.salt/*.nc

Tuomas Karna 2013-01-07
"""

# just a wrapper to parseCommandLine method
from crane.plotting import generateTimeSeriesPlot

if __name__=='__main__' :
  generateTimeSeriesPlot.parseCommandLine()
