#!/usr/bin/env python
"""
Reads dataContainer from netcdf file and prints summary on stdout.

Tuomas Karna 2014-10-30
"""
from data.dataContainer import dataContainer
from optparse import OptionParser

#-------------------------------------------------------------------------
# Parse commandline arguments
#-------------------------------------------------------------------------
if __name__ == '__main__':

    usage = ('Usage: %prog dataContainerFile\n')

    parser = OptionParser(usage=usage)
    (options, args) = parser.parse_args()

    if len(args) < 1:
        parser.print_help()
        parser.error('argument missing')

    fname = args[0]
    dc = dataContainer.loadFromNetCDF(fname)
    print dc
