#!/usr/bin/env python
"""
Computes element quality measures and reports worst elements

Tuomas Karna 2014-06-18
"""

# just a wrapper to parseCommandLine method
from data.reportMeshQuality import *

if __name__=='__main__' :
  parseCommandLine()
