#!/usr/bin/env python
"""
Computes element quality measures and reports worst elements

Tuomas Karna 2014-06-18
"""

# just a wrapper to parseCommandLine method
from crane.data import reportMeshQuality

if __name__=='__main__' :
  reportMeshQuality.parseCommandLine()
