#!/usr/bin/env python
"""
Plots volume/tracer mass conservation for each region in flux partitioning.
Also plots fluxes and fluxes corrected to match volume changes.

Tuomas Karna 2014-10-29
"""

# just a wrapper to parseCommandLine method
from data.testFluxConservation import *

if __name__=='__main__' :
  parseCommandLine()
