#!/usr/bin/env python
"""
Converts tag/data directory to match the new convention.

Examples:

Process tag 'obs':
./updateNetCDFFileTree obs

Process tags 'obs' and 'run127':
./updateNetCDFFileTree obs run127

Tuomas Karna 2013-01-23
"""

import shutil
import os
from optparse import OptionParser

from data.stationCollection import StationCollection
from data.dirTreeManager import oldTreeRule, defaultTreeRule

if __name__=='__main__' :
  
  usage = ('Usage: %prog  runID1 runID2 ...\n')

  parser = OptionParser(usage=usage)

  (options, args) = parser.parse_args()

  if not args :
    #parser.print_help()
    parser.error('runID missing')

  tags = args

  for tag in tags :
    newDir = 'data_new'
    oldDir = 'data'
    tmpDir = 'data_old'
    oldPath = os.path.join(tag,oldDir)
    newPath = os.path.join(tag,newDir)
    tmpPath = os.path.join(tag,tmpDir)

    sc = StationCollection.loadFromNetCDFCollection( tag=tag,
                                      treeRule=oldTreeRule(dataDir=oldDir) )
    if len(sc.data) == 0 :
      print 'no data found for:',tag
      continue
    sc.saveAsNetCDFCollection( dataDir=newDir, treeType='default' )

    sc2 = StationCollection.loadFromNetCDFCollection( tag=tag,treeRule=defaultTreeRule(dataDir=newDir) )

    # compare all keys in the collections
    success = True
    for k in sc.getKeys() :
      dc1 = sc.getSample(k)
      dc2 = sc2.getSample(k)
      if dc1 != dc2 :
        print '* comparison failed'
        print dc1
        print dc2
        success = False
    if success :
      print ' * data verification successful'
      print ' - moving',oldPath,'->',tmpPath
      os.rename( oldPath,tmpPath )
      print ' - moving',newPath,'->',oldPath
      os.rename( newPath,oldPath )
      print ' -',tmpPath,'can be removed'
      print ' * migration finished'
    else :
      print ' ** verification FAILED'

